// The `rgit completion` command surface: prints a shell completion script
// for bash or zsh. There is nothing to resolve or synthesize here, so
// unlike diff and commit this needs no repository at all -- see
// docs/USAGE.md § Shell completion.
package app

import (
	"fmt"
	"io"

	"github.com/Rethunk-Tech/rethunk-git-cli/internal/exitcode"
)

const completionHelp = `usage: rgit completion <bash|zsh>

Print a shell completion script for that shell to stdout.

  bash: source <(rgit completion bash)
  zsh:  source <(rgit completion zsh)   # after compinit has run

Persistent installation: docs/INSTALL.md § Shell completion.
`

func runCompletion(args []string, stdout, stderr io.Writer) exitcode.Code {
	if len(args) == 1 && (args[0] == "--help" || args[0] == "-h") {
		fmt.Fprint(stdout, completionHelp)
		return exitcode.Success
	}
	if len(args) != 1 {
		fmt.Fprintln(stderr, "rgit: completion requires exactly one shell argument (bash or zsh)")
		fmt.Fprint(stderr, completionHelp)
		return exitcode.InvalidUsage
	}
	switch args[0] {
	case "bash":
		fmt.Fprint(stdout, bashCompletionScript)
		return exitcode.Success
	case "zsh":
		fmt.Fprint(stdout, zshCompletionScript)
		return exitcode.Success
	default:
		fmt.Fprintf(stderr, "rgit: unknown shell %q; supported: bash, zsh\n", args[0])
		return exitcode.InvalidUsage
	}
}

// rgitDiffFlags and rgitCommitFlags are the static parts of completion:
// each subcommand's own flag surface, mirroring docs/USAGE.md § Flags plus
// the --sym/--file pair every subcommand shares (internal/app/shared.go's
// newTargetFlagSet). They are duplicated here rather than introspected from
// the live pflag.FlagSet because the completion script is a standalone text
// blob with no Go runtime behind it once emitted -- keep this in sync with
// diff.go and commit.go's own flag registration by hand.
const rgitDiffFlags = "--unstaged --staged --cached --range --porcelain --exit-code --quiet --sym --file --help"

const rgitCommitFlags = "-m --message -F --message-file -s --signoff --trailer --amend --allow-empty --push " +
	"--dry-run --no-verify --fixup --squash --author --date --reset-author --porcelain -q --quiet " +
	"-S --gpg-sign --no-gpg-sign --sym --file --help"

// bashCompletionScript is emitted verbatim by `rgit completion bash`. The
// one dynamic piece -- symbol names after "FILE:" -- shells back out to
// `rgit diff --porcelain` and cuts its SYMBOL column for the matching FILE
// (docs/CODES.md § Output records), so completion can never name a symbol
// `rgit commit` would not itself accept. Any failure of that call (not a
// repo, rgit not on PATH, anything) is swallowed by the 2>/dev/null and
// leaves the candidate list empty -- completion must never put an error on
// the prompt.
const bashCompletionScript = `# rgit bash completion -- generated by ` + "`rgit completion bash`" + `.
# Load once:  source <(rgit completion bash)
# Persist:    rgit completion bash > ~/.local/share/bash-completion/completions/rgit

_rgit_diff_flags="` + rgitDiffFlags + `"
_rgit_commit_flags="` + rgitCommitFlags + `"

_rgit_symbols() {
    rgit diff --porcelain 2>/dev/null | awk -F'\t' -v f="$1" '$1 == f && $2 != "" { print $2 }'
}

_rgit_completion() {
    local cur cmd
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    cmd="${COMP_WORDS[1]}"

    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "diff commit completion help --help --version" -- "$cur") )
        return 0
    fi

    local flags=""
    case "$cmd" in
        diff) flags="$_rgit_diff_flags" ;;
        commit) flags="$_rgit_commit_flags" ;;
        completion)
            if [[ $COMP_CWORD -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "bash zsh" -- "$cur") )
            fi
            return 0
            ;;
        *) return 0 ;;
    esac

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
    fi

    if [[ "$cur" == *:* ]]; then
        local file="${cur%:*}" symprefix="${cur##*:}"
        COMPREPLY=( $(compgen -P "${file}:" -W "$(_rgit_symbols "$file")" -- "$symprefix") )
        return 0
    fi

    COMPREPLY=( $(compgen -f -- "$cur") )
}

complete -F _rgit_completion rgit
`

// zshCompletionScript is `rgit completion zsh`'s output. It is a plain
// compadd-based completer rather than the _arguments/_describe machinery,
// since the shape here (one flag list per subcommand, one dynamic lookup)
// does not need it -- see bashCompletionScript's doc comment for the
// dynamic-symbol contract, identical here.
const zshCompletionScript = `#compdef rgit
# rgit zsh completion -- generated by ` + "`rgit completion zsh`" + `.
# Load once (after compinit): source <(rgit completion zsh)
# Persist: rgit completion zsh > "$fpath[1]/_rgit", then re-run compinit

_rgit_diff_flags=(` + rgitDiffFlags + `)
_rgit_commit_flags=(` + rgitCommitFlags + `)

_rgit_symbols() {
    rgit diff --porcelain 2>/dev/null | awk -F'\t' -v f="$1" '$1 == f && $2 != "" { print $2 }'
}

_rgit() {
    local cur cmd
    cur="${words[CURRENT]}"
    cmd="${words[2]}"

    if (( CURRENT == 2 )); then
        compadd -- diff commit completion help --help --version
        return
    fi

    local -a flags
    case "$cmd" in
        diff) flags=("${_rgit_diff_flags[@]}") ;;
        commit) flags=("${_rgit_commit_flags[@]}") ;;
        completion)
            if (( CURRENT == 3 )); then
                compadd -- bash zsh
            fi
            return
            ;;
        *) return ;;
    esac

    if [[ "$cur" == -* ]]; then
        compadd -- "${flags[@]}"
        return
    fi

    if [[ "$cur" == *:* ]]; then
        local file="${cur%:*}"
        local out
        out="$(_rgit_symbols "$file")"
        # Splitting "" with (f) still yields one empty element, not zero
        # -- guard it, or a file with no candidates offers a bare "FILE:".
        # Narrowing candidates against what's already typed after the
        # colon is compadd's own job here, the same as it already is for
        # the flag and subcommand lists above -- zsh's completion system
        # matches added candidates against the current word automatically,
        # unlike bash's compgen, which needs "-- $cur" to do it explicitly.
        if [[ -n "$out" ]]; then
            local -a syms
            syms=("${(@f)out}")
            compadd -P "${file}:" -- "${syms[@]}"
        fi
        return
    fi

    _files
}

(( $+functions[compdef] )) && compdef _rgit rgit
`
